#  VULNERABLE httpd.conf for CVE-2021-41773 lab
#  Two conditions make this vulnerable:
#    1. Apache version == 2.4.49  (baked into the Docker image)
#    2. "Require all granted" on the root directory (below)


ServerRoot "/usr/local/apache2"
Listen 80

LoadModule mpm_event_module   modules/mod_mpm_event.so
LoadModule unixd_module       modules/mod_unixd.so
LoadModule authz_core_module  modules/mod_authz_core.so
LoadModule authz_host_module  modules/mod_authz_host.so
LoadModule log_config_module  modules/mod_log_config.so
LoadModule mime_module        modules/mod_mime.so
LoadModule dir_module         modules/mod_dir.so
LoadModule alias_module       modules/mod_alias.so
LoadModule cgi_module         modules/mod_cgi.so

ServerAdmin you@example.com
ServerName localhost

<Directory />
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

DocumentRoot "/usr/local/apache2/htdocs"

<Directory "/usr/local/apache2/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

Alias /static/ "/"

ScriptAlias /cgi-bin/ "/usr/local/apache2/cgi-bin/"

<Directory "/usr/local/apache2/cgi-bin">
    Options +ExecCGI
    AllowOverride None
    Require all granted
    AddHandler cgi-script .cgi .sh
</Directory>

User daemon
Group daemon

ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 combined

TypesConfig conf/mime.types